#mobilerobot:
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

oriental_position_controller:
  type: position_controllers/JointPositionController
  joint: ball_screw_joint  

mobile_chassis_velocity_controller:
  type: "mecanum_wheel_controller/MecanumWheelController"
  front_left_wheel_joint: "forward_left_joint"
  front_right_wheel_joint: "forward_right_joint"
  back_left_wheel_joint: "backward_left_joint"
  back_right_wheel_joint: "backward_right_joint"
  
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  # Override URDF look-up for wheel separation since the parent link is not the base_link.
  wheel_separation_x: 0.3
  wheel_separation_y: 0.3

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.15   # m/s
      has_acceleration_limits: false
      max_acceleration       : 0.1    # m/s^2
    y:
      has_velocity_limits    : true
      max_velocity           : 0.15   # m/s
      has_acceleration_limits: false
      max_acceleration       : 0.1    # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.2   # rad/s
      has_acceleration_limits: false
      max_acceleration       : 0.1   # rad/s^2

manipulaotr_trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7

  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.05

    joint1: {trajectory: 0.1, goal: 0.1}
    joint2: {trajectory: 0.1, goal: 0.1}
    joint3: {trajectory: 0.1, goal: 0.1}
    joint4: {trajectory: 0.1, goal: 0.1}
    joint5: {trajectory: 0.1, goal: 0.1}
    joint6: {trajectory: 0.1, goal: 0.1}
    joint7: {trajectory: 0.1, goal: 0.1}
  
  stop_trajectory_duration: 0.5
  state_publish_rate: 125
  action_monitor_rate: 10

  gains:
    joint1: {p: 10,  d: 1, i: 1, i_clamp: 1}
    joint2: {p: 10,  d: 1, i: 1, i_clamp: 1}
    joint3: {p: 10,  d: 1, i: 1, i_clamp: 1}
    joint4: {p: 10,  d: 1, i: 1, i_clamp: 1}
    joint5: {p: 10,  d: 1, i: 1, i_clamp: 1}
    joint6: {p: 10,  d: 1, i: 1, i_clamp: 1}
    joint7: {p: 10,  d: 1, i: 1, i_clamp: 1}
