controller_list:
  - name: manipualtor
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - ball_screw_joint
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7